/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalencryption;

import static finalencryption.Form.decryptFileChooser;
import static finalencryption.Form.encryptMethod;
import static finalencryption.Form.fileChooser;
import static finalencryption.Form.outFile;
import static finalencryption.Form.textForTextArea;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Yousha Arif
 */
public class MukhFee extends javax.swing.JFrame {

    static JFileChooser fileChooser = new JFileChooser();
    static JFileChooser decryptFileChooser,unlockFileChooser;
    static PrintWriter outFile ;
    static String path ;
    static File aFile,newFile,encryptFile,lockFile ;
    static String textForTextArea= "";
    static double [] LETTER  = new double[1000];
    static String TEMP ;
    static String fileParentPath ;
    private static Scanner inFile;
    private static int wordConstraint ; 
    
    /**
     * Creates new form MukhFee
     */
    public MukhFee() {
        initComponents();
        addFilePanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        homePanel = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        addFileLabel = new javax.swing.JLabel();
        decryptFileLabel = new javax.swing.JLabel();
        lockFileLabel = new javax.swing.JLabel();
        UnlockFileLabel = new javax.swing.JLabel();
        homePageLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        defaultScreenPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addFilePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        encryptFileLabel = new javax.swing.JLabel();
        wordsLeftLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mukh-Fee V 1.1.0");
        setBackground(java.awt.SystemColor.controlLtHighlight);
        setMinimumSize(new java.awt.Dimension(800, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopPanel.setBackground(new java.awt.Color(101, 157, 179));
        TopPanel.setLayout(null);

        addFileLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yousha Arif\\Desktop\\Add File_30px.png")); // NOI18N
        addFileLabel.setToolTipText("Add File");
        addFileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addFileLabelMouseClicked(evt);
            }
        });
        TopPanel.add(addFileLabel);
        addFileLabel.setBounds(331, 11, 38, 48);

        decryptFileLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yousha Arif\\Desktop\\View Details_30px.png")); // NOI18N
        decryptFileLabel.setToolTipText("Decrypt File");
        decryptFileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                decryptFileLabelMouseClicked(evt);
            }
        });
        TopPanel.add(decryptFileLabel);
        decryptFileLabel.setBounds(387, 11, 39, 48);

        lockFileLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yousha Arif\\Desktop\\Lock_30px.png")); // NOI18N
        lockFileLabel.setToolTipText("Lock File");
        lockFileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lockFileLabelMouseClicked(evt);
            }
        });
        TopPanel.add(lockFileLabel);
        lockFileLabel.setBounds(440, 13, 40, 40);

        UnlockFileLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yousha Arif\\Desktop\\Unlock_30px.png")); // NOI18N
        UnlockFileLabel.setToolTipText("Unlock FIle");
        UnlockFileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UnlockFileLabelMouseClicked(evt);
            }
        });
        TopPanel.add(UnlockFileLabel);
        UnlockFileLabel.setBounds(500, 12, 40, 40);

        homePageLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yousha Arif\\Desktop\\Home_30px.png")); // NOI18N
        homePageLabel.setToolTipText("Home");
        homePageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePageLabelMouseClicked(evt);
            }
        });
        TopPanel.add(homePageLabel);
        homePageLabel.setBounds(550, 12, 40, 40);

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel6.setText("Mukh-");
        TopPanel.add(jLabel6);
        jLabel6.setBounds(50, 10, 100, 40);

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setText("Fee");
        TopPanel.add(jLabel7);
        jLabel7.setBounds(120, 7, 100, 44);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yousha Arif\\Desktop\\Spy Male_30px.png")); // NOI18N
        TopPanel.add(jLabel8);
        jLabel8.setBounds(10, 5, 34, 50);

        homePanel.add(TopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 70));

        defaultScreenPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Secure Your Data");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yousha Arif\\Desktop\\Spy Male_96px.png")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("With");

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        jLabel4.setText("Mukh-");

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 255));
        jLabel5.setText("Fee");

        javax.swing.GroupLayout defaultScreenPanelLayout = new javax.swing.GroupLayout(defaultScreenPanel);
        defaultScreenPanel.setLayout(defaultScreenPanelLayout);
        defaultScreenPanelLayout.setHorizontalGroup(
            defaultScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, defaultScreenPanelLayout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(defaultScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(defaultScreenPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(182, 182, 182))
        );
        defaultScreenPanelLayout.setVerticalGroup(
            defaultScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultScreenPanelLayout.createSequentialGroup()
                .addGroup(defaultScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(defaultScreenPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(defaultScreenPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(defaultScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        homePanel.add(defaultScreenPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 800, 300));

        addFilePanel.setBackground(new java.awt.Color(255, 255, 255));
        addFilePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 255)));
        jScrollPane1.setViewportView(jTextArea1);

        encryptFileLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        encryptFileLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yousha Arif\\Desktop\\Data Recovery_15px.png")); // NOI18N
        encryptFileLabel.setText(" Encrypt");
        encryptFileLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 204), new java.awt.Color(0, 153, 255), new java.awt.Color(0, 153, 204), new java.awt.Color(0, 153, 204)));
        encryptFileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encryptFileLabelMouseClicked(evt);
            }
        });

        wordsLeftLabel.setBackground(new java.awt.Color(255, 255, 255));
        wordsLeftLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout addFilePanelLayout = new javax.swing.GroupLayout(addFilePanel);
        addFilePanel.setLayout(addFilePanelLayout);
        addFilePanelLayout.setHorizontalGroup(
            addFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addFilePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addFilePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(wordsLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(418, 418, 418)
                        .addComponent(encryptFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(294, 294, 294))
        );
        addFilePanelLayout.setVerticalGroup(
            addFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addFilePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addFilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encryptFileLabel)
                    .addComponent(wordsLeftLabel))
                .addContainerGap())
        );

        homePanel.add(addFilePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 740, 260));

        getContentPane().add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 368));

        jMenuBar1.setName(" "); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 31));

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yousha Arif\\Desktop\\Plus_15px.png")); // NOI18N
        jMenu1.setText("File");

        jMenuItem1.setText("Add File");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addFileLabelMouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Lock File");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lockFileLabelMouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Unlock File");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UnlockFileLabelMouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem5.setText("About Us");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addFileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addFileLabelMouseClicked
        defaultScreenPanel.setVisible(false);
        addFilePanel.setVisible(true);
        //****************************LOGIC******************************************//
         fileChooser.setFileFilter(new FileNameExtensionFilter("*.txt","txt"));
         fileChooser.showOpenDialog(null);
         aFile = fileChooser.getSelectedFile();
         path = aFile.getAbsolutePath();
         
         try 
        {
           jTextArea1.setText(addFileMethod(path));
           if(jTextArea1.getText().length()>999)
           {
               JOptionPane.showMessageDialog(rootPane, "Word Limit Exceeded");
               System.exit(0);
           }
           else
           {
               wordConstraint =1000-jTextArea1.getText().length();
               wordsLeftLabel.setText("Words Limit: "+wordConstraint+""+"/1000");
           }
           
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_addFileLabelMouseClicked

    private void decryptFileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_decryptFileLabelMouseClicked
         defaultScreenPanel.setVisible(false);
        addFilePanel.setVisible(true);
        encryptFileLabel.setVisible(false);
        
        //**************************LOGIC******************************//
        decryptFileChooser = new JFileChooser();
       decryptFileChooser.setFileFilter(new FileNameExtensionFilter("(*.txt)Text Files", "txt"));
       decryptFileChooser.showOpenDialog(null);
       encryptFile = decryptFileChooser.getSelectedFile();
        try {
            jTextArea1.setText(decryptMethod(encryptFile.getAbsolutePath()));
       } catch (FileNotFoundException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);}
        JOptionPane.showMessageDialog(rootPane, "Text Successfully Decrypted");
    }//GEN-LAST:event_decryptFileLabelMouseClicked

    private void encryptFileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encryptFileLabelMouseClicked
         try {
            
            jTextArea1.setText("");
            encryptMethod(textForTextArea, path);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Sorry an error occured \n "+ex);
        }
        JOptionPane.showMessageDialog(rootPane, "Data Successfully encrypted");
    }//GEN-LAST:event_encryptFileLabelMouseClicked

    private void lockFileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lockFileLabelMouseClicked
         displayHomeScreen();  
        fileChooser.setFileFilter(new FileNameExtensionFilter("*.txt","txt"));
          fileChooser.showOpenDialog(null);
          lockFile = fileChooser.getSelectedFile();
        try {
            lockFileMethod(lockFile);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MukhFee.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        
    }//GEN-LAST:event_lockFileLabelMouseClicked

    private void UnlockFileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UnlockFileLabelMouseClicked
          displayHomeScreen();
         unlockFileChooser = new JFileChooser();
         unlockFileChooser.setFileFilter(new FileNameExtensionFilter("(*.enc)Encrypted Files ", "enc"));
         unlockFileChooser.showOpenDialog(null);
        try {
            unlockFileMethod(unlockFileChooser.getSelectedFile());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MukhFee.class.getName()).log(Level.SEVERE, null, ex);
        }
         
         
    }//GEN-LAST:event_UnlockFileLabelMouseClicked

    private void homePageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePageLabelMouseClicked
         displayHomeScreen();
       // defaultScreenPanel.setVisible(true);
       //  addFilePanel.setVisible(false);
         
         
    }//GEN-LAST:event_homePageLabelMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        fileChooser.setFileFilter(new FileNameExtensionFilter("*.txt","txt"));
          fileChooser.showOpenDialog(null);
          lockFile = fileChooser.getSelectedFile();
        try {
            lockFileMethod(lockFile);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MukhFee.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JOptionPane.showMessageDialog(rootPane,"Developed By Ababeel \n V 1.0.0");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         defaultScreenPanel.setVisible(false);
        addFilePanel.setVisible(true);
        //****************************LOGIC******************************************//
         fileChooser.setFileFilter(new FileNameExtensionFilter("*.txt","txt"));
         fileChooser.showOpenDialog(null);
         aFile = fileChooser.getSelectedFile();
         path = aFile.getAbsolutePath();
         
         try 
        {
           jTextArea1.setText(addFileMethod(path));    
        }
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        unlockFileChooser = new JFileChooser();
         unlockFileChooser.setFileFilter(new FileNameExtensionFilter("(*.enc)Encrypted Files ", "enc"));
         unlockFileChooser.showOpenDialog(null);
        try {
            unlockFileMethod(unlockFileChooser.getSelectedFile());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MukhFee.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    //****************************************************************//
    //+++++++++++++++++++METHODS DECLARATION+++++++++++++++++++++++++//
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++///
    public static String decryptMethod(String pathOfFileToBeDecrypted) throws FileNotFoundException
    {
       inFile = new Scanner(new FileReader(pathOfFileToBeDecrypted));;
       String LETTER = "" ;
       String DECRYPTED_LETTER = "";
      
           while(inFile.hasNext())
        {
       LETTER = inFile.next();//1245?8
       int indexOfN = LETTER.indexOf("?") ;
       int n = Integer.parseInt(LETTER.substring(indexOfN+1)) ;
       float valueOfN = (float) (1.0/n);
       double orgLETTER = Double.parseDouble(LETTER.substring(0,indexOfN));
       int neworgLETTER  =(int)Math.pow(orgLETTER,valueOfN);
       DECRYPTED_LETTER += (char)neworgLETTER;
       
       //jTextField1.setText(DECRYPTED_LETTER.replaceFirst("null", ""));
      }
      return DECRYPTED_LETTER;     
    }
     public static void encryptMethod(String textToEncrypt,String path) throws FileNotFoundException
    {
        outFile = new PrintWriter(path);
        TEMP = textToEncrypt; 
       
         for (int i = 0; i < TEMP.length() ; i++) 
         {
            
               LETTER[i] = (int)TEMP.charAt(i) ;
       
              int randomNumber = (int)(Math.random()*10+1);
       
              LETTER[i] =  Math.pow(LETTER[i],randomNumber);
       
              outFile.println(LETTER[i]+"?"+randomNumber+"");
          
        }
       outFile.close();
       
    }
      public static String addFileMethod(String path) throws FileNotFoundException // it reads file and display it on textArea
    {
          
        try (Scanner inFile = new Scanner(new FileReader(path))) {
            while(inFile.hasNext())
            {
                textForTextArea += inFile.next()+" ";
            }
        }
         
       return textForTextArea;
    }
      public static void lockFileMethod(File fileToBeLocked) throws FileNotFoundException
      {
          String parentpath = fileToBeLocked.getParent(); //File Dir
          String fileName = fileToBeLocked.getName();     //fileName.xyz
          StringBuilder sbFileName = new StringBuilder(fileName); // for removing extension
          sbFileName.replace(fileName.indexOf("."),fileName.length(), ""); //.......still removing
       
          newFile = new File(parentpath, new String(sbFileName+".enc")); //creating encrypted File
        try {
            newFile.createNewFile(); 
        } catch (IOException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        }
       // To store the data of previous file in new encrypted file
        Scanner readFromFileToBeLocked = new Scanner(new FileReader(fileToBeLocked));
        PrintWriter writeOnLockedFile = new PrintWriter(newFile);
        while(readFromFileToBeLocked.hasNext())
        {writeOnLockedFile.println(readFromFileToBeLocked.next()+" ");}
        writeOnLockedFile.close();
        readFromFileToBeLocked.close();
         
        try
        { addFileMethod(newFile.getAbsolutePath());
          encryptMethod(textForTextArea, newFile.getAbsolutePath());
          fileToBeLocked.delete(); 
        }
        catch(Exception e )
        { JOptionPane.showMessageDialog(fileChooser, "Sorry an error occured : \n"+e);
        }
        
        
      }

    /**
     *
     * @param fileToBeUnlocked
     * @throws FileNotFoundException
     */
    public static void unlockFileMethod(File fileToBeUnlocked) throws FileNotFoundException
      {
          String parentpath = fileToBeUnlocked.getParent(); //File Dir
          String fileName = fileToBeUnlocked.getName();     //fileName.xyz
          StringBuilder sbFileName = new StringBuilder(fileName); // for removing extension
          sbFileName.replace(fileName.indexOf("."),fileName.length(), ""); //.......still removing
       
          newFile = new File(parentpath, new String(sbFileName+".txt")); //creating encrypted File
        try {
            newFile.createNewFile(); 
        } catch (IOException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        Scanner readFromLockedFile = new Scanner(new FileReader(fileToBeUnlocked));
        PrintWriter writeOnFileToBeUnlocked = new PrintWriter(newFile);
            
        String textOfLockedFile = decryptMethod(fileToBeUnlocked.getAbsolutePath());
       // while(readFromFileToBeLocked.hasNext())
        //{
          //textOfLockedFile += readFromLockedFile.next()+" " ; //think wht it was giving error
                //}
        writeOnFileToBeUnlocked.print(textOfLockedFile);
        writeOnFileToBeUnlocked.close();
        readFromLockedFile.close();
        fileToBeUnlocked.delete();
      }
    //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++//
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++//
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MukhFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MukhFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MukhFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MukhFee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MukhFee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TopPanel;
    private javax.swing.JLabel UnlockFileLabel;
    private javax.swing.JLabel addFileLabel;
    private javax.swing.JPanel addFilePanel;
    private javax.swing.JLabel decryptFileLabel;
    private javax.swing.JPanel defaultScreenPanel;
    private javax.swing.JLabel encryptFileLabel;
    private javax.swing.JLabel homePageLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lockFileLabel;
    private javax.swing.JLabel wordsLeftLabel;
    // End of variables declaration//GEN-END:variables

    private void displayHomeScreen() {
       defaultScreenPanel.setVisible(true);
         addFilePanel.setVisible(false);
    }
}
